language: bash
sudo: required
branches:
  only:
  - master
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_d15bcc7ddde5_key -iv $encrypted_d15bcc7ddde5_iv
  -in onestoop-73f05c458f5a.json.enc -out onestoop-73f05c458f5a.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: "onestoop-73f05c458f5a.json"
  project: "onestoop-fe7eb"
  no_promote: true
  on:
    branch: master
