language: bash
sudo: required
branches:
  only:
  - master
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_94b7d3a19d35_key -iv $encrypted_94b7d3a19d35_iv
  -in onestoop-fe7eb-0059586fba52.json.enc -out onestoop-fe7eb-0059586fba52.json -d
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: onestoop-fe7eb-0059586fba52.json
  project: onestoop-fe7eb
  no_promote: true
  on:
    branch: master
