language: bash

sudo: required

branches:
  only:
  - master

services:
- docker

before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t onestoop/osapi:$TRAVIS_BUILD_NUMBER .
  - docker push onestoop/osapi

script:
- bash scripts/updateKube.sh

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
