apiVersion: apps/v1
kind: Deployment
metadata:
  name: osapi
  namespace: default
  labels:
    app: osapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: osapi
  template:
    metadata:
      labels:
        app: osapi
    spec:
      containers:
        - name: osapi
          image: onestoop/osapi:{{VERSION}}
          ports:
            - containerPort: 80
              name: http
          env:
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: baseurl
            - name: ARANGODB_SETTINGS
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: arangodbsettings
            - name: FIREBASE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: firebaseconfig
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: spaceskey
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: spacessecret
