apiVersion: v1
kind: Service
metadata:
  name: osapi
  namespace: default
  labels:
    app: osapi
spec:
  selector:
    app: osapi
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

