apiVersion: v1
kind: Service
metadata:
  name: osapi
  namespace: default
  labels:
    app: osapi
spec:
  selector:
    app: osapi
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      name: https

